class Pin:
    OUT: int
    IN: int
    PULL_UP: int
    PULL_DOWN: int

    def __init__(self, id: int, mode: int | None = None, pull: int | None = None): ...
    def value(self, value: int | None = None) -> int: ...


class I2C:
    def __init__(self, id: int, *, sda: Pin, scl: Pin, freq: int = 400000): ...
    def readfrom_mem(self, addr: int, memaddr: int, nbytes: int) -> bytes: ...
    def writeto_mem(self, addr: int, memaddr: int, buf: bytes | bytearray) -> None: ...


class WDT:
    def __init__(self, *, timeout: int): ...
    def feed(self) -> None: ...


class ADC:
    ATTN_11DB: int

    def __init__(self, pin: Pin): ...
    def atten(self, attenuation: int) -> None: ...
    def read_u16(self) -> int: ...


def reset() -> None: ...
