STA_IF: int


class WLAN:
    def __init__(self, interface_id: int): ...
    def active(self, is_active: bool | None = None) -> bool: ...
    def config(self, *args, **kwargs): ...
    def isconnected(self) -> bool: ...
    def disconnect(self) -> None: ...
    def connect(self, ssid: str, password: str) -> None: ...
    def ifconfig(self) -> tuple[str, str, str, str]: ...
